from enum import Enum

class DateFormat(Enum):
    """
    Date Format Enum
    """
    YEAR_MONTH_DAY = 1
    YEAR_DAY_MONTH = 2
    MONTH_YEAR_DAY = 3
    MONTH_DAY_YEAR = 4
    DAY_MONTH_YEAR = 5
    DAY_YEAR_MONTH = 6
    YEAR_MONTH_DAY_HOUR = 11
    YEAR_DAY_MONTH_HOUR = 12
    MONTH_YEAR_DAY_HOUR = 13
    MONTH_DAY_YEAR_HOUR = 14
    DAY_MONTH_YEAR_HOUR = 15
    DAY_YEAR_MONTH_HOUR = 16
    YEAR_MONTH_DAY_HOUR_MINUTE = 21
    YEAR_DAY_MONTH_HOUR_MINUTE = 22
    MONTH_YEAR_DAY_HOUR_MINUTE = 23
    MONTH_DAY_YEAR_HOUR_MINUTE = 24
    DAY_MONTH_YEAR_HOUR_MINUTE = 25
    DAY_YEAR_MONTH_HOUR_MINUTE = 26
    YEAR_MONTH_DAY_HOUR_MINUTE_SECOND = 31
    YEAR_DAY_MONTH_HOUR_MINUTE_SECOND = 32
    MONTH_YEAR_DAY_HOUR_MINUTE_SECOND = 33
    MONTH_DAY_YEAR_HOUR_MINUTE_SECOND = 34
    DAY_MONTH_YEAR_HOUR_MINUTE_SECOND = 35
    DAY_YEAR_MONTH_HOUR_MINUTE_SECOND = 36
    YEAR_MONTH_DAY_HOUR_MINUTE_SECOND_MICROSECOND = 41
    YEAR_DAY_MONTH_HOUR_MINUTE_SECOND_MICROSECOND = 42
    MONTH_YEAR_DAY_HOUR_MINUTE_SECOND_MICROSECOND = 43
    MONTH_DAY_YEAR_HOUR_MINUTE_SECOND_MICROSECOND = 44
    DAY_MONTH_YEAR_HOUR_MINUTE_SECOND_MICROSECOND = 45
    DAY_YEAR_MONTH_HOUR_MINUTE_SECOND_MICROSECOND = 46

    def __str__(self):
        return self.name
    